### ISSUE TITLE
Enhancement Request: Configuration Metadata

### ISSUE THREAD

**Issue by denmitchell** [Tricklebyte/ConfigCore#1]
I just spent some time resolving a stupid issue on my part -- using [FromQuery] rather than [FromRoute] for the appId parameter in my Configuration Api Server.  I noticed that when the ApiProvider is optional, the exception-handling essentially ignores errors and silently fails -- which is acceptable and desired behavior for this provider.  That said, it can make trouble-shooting a little harder.

I know that this isn't standard practice, but what if the ApiSource/Provider optionally could return some basic config metadata for the source/provider?  I was thinking that something like this (at least for the ApiKey approach) would be helpful:
```
{
    "ConfigurationMetadata": {
        "ApiSource": {
            "ConfigUrlVar": "ConfigurationApiUrl", 
            "AppId": "My.Application.Name",
            "AuthType": "ApiKey",
            "AuthSecretVar": "*******1234",
            "RequestUrl": "https://someDomain:1234/someController/My.Application.Name",
            "ResponseStatusCode": 404
        }
    }
}
```
If I had some metadata like this, it would have helped me with troubleshooting.  Again, I know that it isn't standard practice to return metadata, but it would have been helpful for debugging purposes.

As an alternative, possibly hooking into the logging system and logging this info would be fine, but that might be a little bit harder to implement (and make it work for various scenarios, including automated testing).

**Comment by Tricklebyte** [comment]
Thanks for the recommendation. Now I remember thinking that I wanted
generate Warnings instead of Exceptions when optional was true.
You're right though, a real "Warning" message would need to be issued by
some kind of logger and that would complicate things.
I could pretty easily write the HttpResponse error information to the
output window instead of throwing the Exception.

Thanks also for mentioning that you were using query parameters.
I've been using route parameters just because it was the Microsoft default.
I did some reading this morning, and I can see that a query parameter would
be recommended here because we are applying a search filter.
The URI path parameter would be suitable when identifying a resource.

Please let me know if you'd prefer that I leave it the way it is for now
since you're already using it.

**Comment by denmitchell** [comment]
@Tricklebyte, I am going to raise another issue (enhancement request) for this, but I wanted to respond to the path parameter vs. query parameter question.  In isolation, having the appId as a path parameter is nice in a way because you will get a 404 status code if you get the path parameter wrong or missing.  That said, you could always generate a 404 status code (or another 4xx status code) if an appId query parameter was wrong or missing.  And, there may be another reason for using a query parameter ... (see the other issue)

**Comment by Tricklebyte** [comment]
Added to Version 3.0 
Error information is now written to the client in configuration section **ConfigurationMetaData**, but only when optional is true. When optional is false, exceptions are generated that contain the error information.
